### ISSUE TITLE
Add security/performance best practices to ZPA instance/ASG

### ISSUE THREAD

**Issue by twglomski** [zscaler/terraform-aws-zpa-app-connector-modules#14]
When deploying via these modules we noticed the following deficiencies for the ZPA auto-scaling group and instance deploy modules:
- IMDSv2 is not enforced ([details on IMDSv2 and why it is needed](https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/), and [where it is set in Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#metadata-options))
- The EBS root block device is not encrypted, nor is there any setting to encrypt it
- Using GP2 for disk instead of GP3 ([details on why we would want to do that](https://aws.amazon.com/about-aws/whats-new/2020/12/introducing-new-amazon-ebs-general-purpose-volumes-gp3/))

We are working around this right now, but it would be nice to have these options either enabled by default or available as variables.

**Comment by wojciechka** [comment]
+1 to this, I'd really appreciate all the improvements, especially support for IMDSv2

**Comment by wojciechka** [comment]
Just opened #15 for addressing some of the issues here as I need it for terraform code I manage.

Happy to add anything I may have missed or add any changes needed to get this merged and released.
